<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>5ccacbda-bc94-4702-ad5d-28483777cf59</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PMGIS.Api\PMGIS.Api.csproj" />
  </ItemGroup>

</Project>
